#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-ldc-soname95
Version  : 1.25.1
Release  : 36
URL      : https://github.com/ldc-developers/ldc/releases/download/v1.25.1/ldc-1.25.1-src.tar.gz
Source0  : https://github.com/ldc-developers/ldc/releases/download/v1.25.1/ldc-1.25.1-src.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSL-1.0
Requires: compat-ldc-soname95-lib = %{version}-%{release}
Requires: compat-ldc-soname95-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : ldc
BuildRequires : ldc-dev
BuildRequires : libffi-dev
BuildRequires : llvm
BuildRequires : llvm-dev
BuildRequires : llvm-extras
BuildRequires : llvm-staticdev
BuildRequires : ncurses-dev
BuildRequires : pkg-config
Patch1: 0001-Fixups-for-packaging-and-stateless-config.patch
Patch2: 0002-Don-t-force-the-use-of-gold-linker.patch

%description
This is a standalone (DMD-style) binary package for LDC, the LLVM-based D
compiler.

%package lib
Summary: lib components for the compat-ldc-soname95 package.
Group: Libraries
Requires: compat-ldc-soname95-license = %{version}-%{release}

%description lib
lib components for the compat-ldc-soname95 package.


%package license
Summary: license components for the compat-ldc-soname95 package.
Group: Default

%description license
license components for the compat-ldc-soname95 package.


%prep
%setup -q -n ldc-1.25.1-src
cd %{_builddir}/ldc-1.25.1-src
%patch1 -p1
%patch2 -p1

%build
## build_prepend content
#export D_COMPILER=/builddir/build/BUILD/ldc-1.14.0-src/bootstrap/bin/ldc2
#export DMD=/builddir/build/BUILD/ldc-1.14.0-src/bootstrap/bin/ldmd2
#export PATH="/usr/local/bin:/usr/lib64/gcc/x86_64-generic-linux:$PATH:/builddir/build/BUILD/ldc-1.14.0-src/bootstrap/bin"
export CFLAGS="$CFLAGS -fPIC "
export LDFLAGS="$LDFLAGS -fPIC "
export CXXFLAGS="$CXXFLAGS -fPIC"
export LD=/usr/bin/ld
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1628009068
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CC=clang
export CXX=clang++
export LD=ld.gold
CFLAGS=${CFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
CXXFLAGS=${CXXFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
export CFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -Wno-error -Wl,-z,max-page-size=0x1000 -march=westmere -mtune=haswell"
export CXXFLAGS=$CFLAGS
export FFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wno-error -Wl,-z,max-page-size=0x1000 -march=westmere -mtune=haswell"
export FCFLAGS=$FFLAGS
unset LDFLAGS
unset LDFLAGS
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -DLDC_ENABLE_PLUGINS=ON \
-DLDC_WITH_LLD=OFF \
-DBUILD_SHARED_LIBS:BOOL=ON \
-DLDC_DYNAMIC_COMPILE=OFF \
-DSYSCONF_INSTALL_DIR=/usr/share/defaults/etc
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1628009068
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-ldc-soname95
cp %{_builddir}/ldc-1.25.1-src/runtime/druntime/LICENSE.txt %{buildroot}/usr/share/package-licenses/compat-ldc-soname95/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
cp %{_builddir}/ldc-1.25.1-src/runtime/phobos/LICENSE_1_0.txt %{buildroot}/usr/share/package-licenses/compat-ldc-soname95/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
pushd clr-build
%make_install
popd
## Remove excluded files
rm -f %{buildroot}/usr/share/bash-completion/completions/ldc2
rm -f %{buildroot}/usr/bin/ldc-build-runtime
rm -f %{buildroot}/usr/bin/ldc-prune-cache
rm -f %{buildroot}/usr/bin/ldc2
rm -f %{buildroot}/usr/bin/ldmd2
rm -f %{buildroot}/usr/include/d/core/atomic.d
rm -f %{buildroot}/usr/include/d/core/attribute.d
rm -f %{buildroot}/usr/include/d/core/bitop.d
rm -f %{buildroot}/usr/include/d/core/checkedint.d
rm -f %{buildroot}/usr/include/d/core/cpuid.d
rm -f %{buildroot}/usr/include/d/core/demangle.d
rm -f %{buildroot}/usr/include/d/core/exception.d
rm -f %{buildroot}/usr/include/d/core/gc/config.d
rm -f %{buildroot}/usr/include/d/core/gc/gcinterface.d
rm -f %{buildroot}/usr/include/d/core/gc/registry.d
rm -f %{buildroot}/usr/include/d/core/internal/abort.d
rm -f %{buildroot}/usr/include/d/core/internal/array/appending.d
rm -f %{buildroot}/usr/include/d/core/internal/array/capacity.d
rm -f %{buildroot}/usr/include/d/core/internal/array/casting.d
rm -f %{buildroot}/usr/include/d/core/internal/array/comparison.d
rm -f %{buildroot}/usr/include/d/core/internal/array/concatenation.d
rm -f %{buildroot}/usr/include/d/core/internal/array/construction.d
rm -f %{buildroot}/usr/include/d/core/internal/array/equality.d
rm -f %{buildroot}/usr/include/d/core/internal/array/operations.d
rm -f %{buildroot}/usr/include/d/core/internal/array/utils.d
rm -f %{buildroot}/usr/include/d/core/internal/atomic.d
rm -f %{buildroot}/usr/include/d/core/internal/attributes.d
rm -f %{buildroot}/usr/include/d/core/internal/backtrace/dwarf.d
rm -f %{buildroot}/usr/include/d/core/internal/backtrace/elf.d
rm -f %{buildroot}/usr/include/d/core/internal/backtrace/handler.d
rm -f %{buildroot}/usr/include/d/core/internal/backtrace/libunwind.d
rm -f %{buildroot}/usr/include/d/core/internal/backtrace/macho.d
rm -f %{buildroot}/usr/include/d/core/internal/container/array.d
rm -f %{buildroot}/usr/include/d/core/internal/container/common.d
rm -f %{buildroot}/usr/include/d/core/internal/container/hashtab.d
rm -f %{buildroot}/usr/include/d/core/internal/container/treap.d
rm -f %{buildroot}/usr/include/d/core/internal/convert.d
rm -f %{buildroot}/usr/include/d/core/internal/dassert.d
rm -f %{buildroot}/usr/include/d/core/internal/destruction.d
rm -f %{buildroot}/usr/include/d/core/internal/elf/dl.d
rm -f %{buildroot}/usr/include/d/core/internal/elf/io.d
rm -f %{buildroot}/usr/include/d/core/internal/entrypoint.d
rm -f %{buildroot}/usr/include/d/core/internal/execinfo.d
rm -f %{buildroot}/usr/include/d/core/internal/hash.d
rm -f %{buildroot}/usr/include/d/core/internal/lifetime.d
rm -f %{buildroot}/usr/include/d/core/internal/moving.d
rm -f %{buildroot}/usr/include/d/core/internal/parseoptions.d
rm -f %{buildroot}/usr/include/d/core/internal/postblit.d
rm -f %{buildroot}/usr/include/d/core/internal/qsort.d
rm -f %{buildroot}/usr/include/d/core/internal/spinlock.d
rm -f %{buildroot}/usr/include/d/core/internal/string.d
rm -f %{buildroot}/usr/include/d/core/internal/switch_.d
rm -f %{buildroot}/usr/include/d/core/internal/traits.d
rm -f %{buildroot}/usr/include/d/core/internal/utf.d
rm -f %{buildroot}/usr/include/d/core/internal/util/array.d
rm -f %{buildroot}/usr/include/d/core/internal/vararg/aarch64.d
rm -f %{buildroot}/usr/include/d/core/internal/vararg/sysv_x64.d
rm -f %{buildroot}/usr/include/d/core/lifetime.d
rm -f %{buildroot}/usr/include/d/core/math.d
rm -f %{buildroot}/usr/include/d/core/memory.d
rm -f %{buildroot}/usr/include/d/core/runtime.d
rm -f %{buildroot}/usr/include/d/core/simd.d
rm -f %{buildroot}/usr/include/d/core/stdc/assert_.d
rm -f %{buildroot}/usr/include/d/core/stdc/complex.d
rm -f %{buildroot}/usr/include/d/core/stdc/config.d
rm -f %{buildroot}/usr/include/d/core/stdc/ctype.d
rm -f %{buildroot}/usr/include/d/core/stdc/errno.d
rm -f %{buildroot}/usr/include/d/core/stdc/fenv.d
rm -f %{buildroot}/usr/include/d/core/stdc/float_.d
rm -f %{buildroot}/usr/include/d/core/stdc/inttypes.d
rm -f %{buildroot}/usr/include/d/core/stdc/limits.d
rm -f %{buildroot}/usr/include/d/core/stdc/locale.d
rm -f %{buildroot}/usr/include/d/core/stdc/math.d
rm -f %{buildroot}/usr/include/d/core/stdc/signal.d
rm -f %{buildroot}/usr/include/d/core/stdc/stdarg.d
rm -f %{buildroot}/usr/include/d/core/stdc/stddef.d
rm -f %{buildroot}/usr/include/d/core/stdc/stdint.d
rm -f %{buildroot}/usr/include/d/core/stdc/stdio.d
rm -f %{buildroot}/usr/include/d/core/stdc/stdlib.d
rm -f %{buildroot}/usr/include/d/core/stdc/string.d
rm -f %{buildroot}/usr/include/d/core/stdc/tgmath.d
rm -f %{buildroot}/usr/include/d/core/stdc/time.d
rm -f %{buildroot}/usr/include/d/core/stdc/wchar_.d
rm -f %{buildroot}/usr/include/d/core/stdc/wctype.d
rm -f %{buildroot}/usr/include/d/core/stdcpp/allocator.d
rm -f %{buildroot}/usr/include/d/core/stdcpp/array.d
rm -f %{buildroot}/usr/include/d/core/stdcpp/exception.d
rm -f %{buildroot}/usr/include/d/core/stdcpp/memory.d
rm -f %{buildroot}/usr/include/d/core/stdcpp/new_.d
rm -f %{buildroot}/usr/include/d/core/stdcpp/string.d
rm -f %{buildroot}/usr/include/d/core/stdcpp/string_view.d
rm -f %{buildroot}/usr/include/d/core/stdcpp/type_traits.d
rm -f %{buildroot}/usr/include/d/core/stdcpp/typeinfo.d
rm -f %{buildroot}/usr/include/d/core/stdcpp/utility.d
rm -f %{buildroot}/usr/include/d/core/stdcpp/vector.d
rm -f %{buildroot}/usr/include/d/core/stdcpp/xutility.d
rm -f %{buildroot}/usr/include/d/core/sync/barrier.d
rm -f %{buildroot}/usr/include/d/core/sync/condition.d
rm -f %{buildroot}/usr/include/d/core/sync/config.d
rm -f %{buildroot}/usr/include/d/core/sync/event.d
rm -f %{buildroot}/usr/include/d/core/sync/exception.d
rm -f %{buildroot}/usr/include/d/core/sync/mutex.d
rm -f %{buildroot}/usr/include/d/core/sync/rwmutex.d
rm -f %{buildroot}/usr/include/d/core/sync/semaphore.d
rm -f %{buildroot}/usr/include/d/core/sys/bionic/err.d
rm -f %{buildroot}/usr/include/d/core/sys/bionic/fcntl.d
rm -f %{buildroot}/usr/include/d/core/sys/bionic/string.d
rm -f %{buildroot}/usr/include/d/core/sys/bionic/unistd.d
rm -f %{buildroot}/usr/include/d/core/sys/darwin/crt_externs.d
rm -f %{buildroot}/usr/include/d/core/sys/darwin/dlfcn.d
rm -f %{buildroot}/usr/include/d/core/sys/darwin/err.d
rm -f %{buildroot}/usr/include/d/core/sys/darwin/execinfo.d
rm -f %{buildroot}/usr/include/d/core/sys/darwin/ifaddrs.d
rm -f %{buildroot}/usr/include/d/core/sys/darwin/mach/dyld.d
rm -f %{buildroot}/usr/include/d/core/sys/darwin/mach/getsect.d
rm -f %{buildroot}/usr/include/d/core/sys/darwin/mach/kern_return.d
rm -f %{buildroot}/usr/include/d/core/sys/darwin/mach/loader.d
rm -f %{buildroot}/usr/include/d/core/sys/darwin/mach/nlist.d
rm -f %{buildroot}/usr/include/d/core/sys/darwin/mach/port.d
rm -f %{buildroot}/usr/include/d/core/sys/darwin/mach/semaphore.d
rm -f %{buildroot}/usr/include/d/core/sys/darwin/mach/stab.d
rm -f %{buildroot}/usr/include/d/core/sys/darwin/mach/thread_act.d
rm -f %{buildroot}/usr/include/d/core/sys/darwin/netinet/in_.d
rm -f %{buildroot}/usr/include/d/core/sys/darwin/pthread.d
rm -f %{buildroot}/usr/include/d/core/sys/darwin/string.d
rm -f %{buildroot}/usr/include/d/core/sys/darwin/sys/attr.d
rm -f %{buildroot}/usr/include/d/core/sys/darwin/sys/cdefs.d
rm -f %{buildroot}/usr/include/d/core/sys/darwin/sys/event.d
rm -f %{buildroot}/usr/include/d/core/sys/darwin/sys/mman.d
rm -f %{buildroot}/usr/include/d/core/sys/dragonflybsd/dlfcn.d
rm -f %{buildroot}/usr/include/d/core/sys/dragonflybsd/err.d
rm -f %{buildroot}/usr/include/d/core/sys/dragonflybsd/execinfo.d
rm -f %{buildroot}/usr/include/d/core/sys/dragonflybsd/netinet/in_.d
rm -f %{buildroot}/usr/include/d/core/sys/dragonflybsd/pthread_np.d
rm -f %{buildroot}/usr/include/d/core/sys/dragonflybsd/string.d
rm -f %{buildroot}/usr/include/d/core/sys/dragonflybsd/sys/_bitset.d
rm -f %{buildroot}/usr/include/d/core/sys/dragonflybsd/sys/_cpuset.d
rm -f %{buildroot}/usr/include/d/core/sys/dragonflybsd/sys/cdefs.d
rm -f %{buildroot}/usr/include/d/core/sys/dragonflybsd/sys/elf.d
rm -f %{buildroot}/usr/include/d/core/sys/dragonflybsd/sys/elf32.d
rm -f %{buildroot}/usr/include/d/core/sys/dragonflybsd/sys/elf64.d
rm -f %{buildroot}/usr/include/d/core/sys/dragonflybsd/sys/elf_common.d
rm -f %{buildroot}/usr/include/d/core/sys/dragonflybsd/sys/event.d
rm -f %{buildroot}/usr/include/d/core/sys/dragonflybsd/sys/link_elf.d
rm -f %{buildroot}/usr/include/d/core/sys/dragonflybsd/sys/mman.d
rm -f %{buildroot}/usr/include/d/core/sys/dragonflybsd/sys/socket.d
rm -f %{buildroot}/usr/include/d/core/sys/dragonflybsd/time.d
rm -f %{buildroot}/usr/include/d/core/sys/freebsd/config.d
rm -f %{buildroot}/usr/include/d/core/sys/freebsd/dlfcn.d
rm -f %{buildroot}/usr/include/d/core/sys/freebsd/err.d
rm -f %{buildroot}/usr/include/d/core/sys/freebsd/execinfo.d
rm -f %{buildroot}/usr/include/d/core/sys/freebsd/netinet/in_.d
rm -f %{buildroot}/usr/include/d/core/sys/freebsd/pthread_np.d
rm -f %{buildroot}/usr/include/d/core/sys/freebsd/string.d
rm -f %{buildroot}/usr/include/d/core/sys/freebsd/sys/_bitset.d
rm -f %{buildroot}/usr/include/d/core/sys/freebsd/sys/_cpuset.d
rm -f %{buildroot}/usr/include/d/core/sys/freebsd/sys/cdefs.d
rm -f %{buildroot}/usr/include/d/core/sys/freebsd/sys/elf.d
rm -f %{buildroot}/usr/include/d/core/sys/freebsd/sys/elf32.d
rm -f %{buildroot}/usr/include/d/core/sys/freebsd/sys/elf64.d
rm -f %{buildroot}/usr/include/d/core/sys/freebsd/sys/elf_common.d
rm -f %{buildroot}/usr/include/d/core/sys/freebsd/sys/event.d
rm -f %{buildroot}/usr/include/d/core/sys/freebsd/sys/link_elf.d
rm -f %{buildroot}/usr/include/d/core/sys/freebsd/sys/mman.d
rm -f %{buildroot}/usr/include/d/core/sys/freebsd/sys/mount.d
rm -f %{buildroot}/usr/include/d/core/sys/freebsd/time.d
rm -f %{buildroot}/usr/include/d/core/sys/freebsd/unistd.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/config.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/dlfcn.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/elf.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/epoll.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/err.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/errno.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/execinfo.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/fcntl.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/ifaddrs.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/link.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/netinet/in_.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/netinet/tcp.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/sched.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/stdio.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/string.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/sys/auxv.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/sys/eventfd.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/sys/file.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/sys/inotify.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/sys/mman.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/sys/prctl.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/sys/signalfd.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/sys/socket.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/sys/sysinfo.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/sys/time.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/sys/xattr.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/termios.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/time.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/timerfd.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/tipc.d
rm -f %{buildroot}/usr/include/d/core/sys/linux/unistd.d
rm -f %{buildroot}/usr/include/d/core/sys/netbsd/dlfcn.d
rm -f %{buildroot}/usr/include/d/core/sys/netbsd/err.d
rm -f %{buildroot}/usr/include/d/core/sys/netbsd/execinfo.d
rm -f %{buildroot}/usr/include/d/core/sys/netbsd/string.d
rm -f %{buildroot}/usr/include/d/core/sys/netbsd/sys/elf.d
rm -f %{buildroot}/usr/include/d/core/sys/netbsd/sys/elf32.d
rm -f %{buildroot}/usr/include/d/core/sys/netbsd/sys/elf64.d
rm -f %{buildroot}/usr/include/d/core/sys/netbsd/sys/elf_common.d
rm -f %{buildroot}/usr/include/d/core/sys/netbsd/sys/event.d
rm -f %{buildroot}/usr/include/d/core/sys/netbsd/sys/featuretest.d
rm -f %{buildroot}/usr/include/d/core/sys/netbsd/sys/link_elf.d
rm -f %{buildroot}/usr/include/d/core/sys/netbsd/sys/mman.d
rm -f %{buildroot}/usr/include/d/core/sys/netbsd/time.d
rm -f %{buildroot}/usr/include/d/core/sys/openbsd/dlfcn.d
rm -f %{buildroot}/usr/include/d/core/sys/openbsd/err.d
rm -f %{buildroot}/usr/include/d/core/sys/openbsd/string.d
rm -f %{buildroot}/usr/include/d/core/sys/openbsd/sys/cdefs.d
rm -f %{buildroot}/usr/include/d/core/sys/openbsd/sys/elf.d
rm -f %{buildroot}/usr/include/d/core/sys/openbsd/sys/elf32.d
rm -f %{buildroot}/usr/include/d/core/sys/openbsd/sys/elf64.d
rm -f %{buildroot}/usr/include/d/core/sys/openbsd/sys/elf_common.d
rm -f %{buildroot}/usr/include/d/core/sys/openbsd/sys/link_elf.d
rm -f %{buildroot}/usr/include/d/core/sys/openbsd/sys/mman.d
rm -f %{buildroot}/usr/include/d/core/sys/openbsd/time.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/aio.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/arpa/inet.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/config.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/dirent.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/dlfcn.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/fcntl.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/grp.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/iconv.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/inttypes.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/libgen.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/locale.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/mqueue.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/net/if_.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/netdb.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/netinet/in_.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/netinet/tcp.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/poll.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/pthread.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/pwd.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/sched.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/semaphore.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/setjmp.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/signal.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/spawn.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/stdc/time.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/stdio.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/stdlib.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/string.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/strings.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/sys/filio.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/sys/ioccom.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/sys/ioctl.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/sys/ipc.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/sys/mman.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/sys/msg.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/sys/resource.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/sys/select.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/sys/shm.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/sys/socket.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/sys/stat.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/sys/statvfs.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/sys/time.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/sys/ttycom.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/sys/types.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/sys/uio.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/sys/un.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/sys/utsname.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/sys/wait.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/syslog.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/termios.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/time.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/ucontext.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/unistd.d
rm -f %{buildroot}/usr/include/d/core/sys/posix/utime.d
rm -f %{buildroot}/usr/include/d/core/sys/solaris/dlfcn.d
rm -f %{buildroot}/usr/include/d/core/sys/solaris/elf.d
rm -f %{buildroot}/usr/include/d/core/sys/solaris/err.d
rm -f %{buildroot}/usr/include/d/core/sys/solaris/execinfo.d
rm -f %{buildroot}/usr/include/d/core/sys/solaris/libelf.d
rm -f %{buildroot}/usr/include/d/core/sys/solaris/link.d
rm -f %{buildroot}/usr/include/d/core/sys/solaris/sys/elf.d
rm -f %{buildroot}/usr/include/d/core/sys/solaris/sys/elf_386.d
rm -f %{buildroot}/usr/include/d/core/sys/solaris/sys/elf_SPARC.d
rm -f %{buildroot}/usr/include/d/core/sys/solaris/sys/elf_amd64.d
rm -f %{buildroot}/usr/include/d/core/sys/solaris/sys/elf_notes.d
rm -f %{buildroot}/usr/include/d/core/sys/solaris/sys/elftypes.d
rm -f %{buildroot}/usr/include/d/core/sys/solaris/sys/link.d
rm -f %{buildroot}/usr/include/d/core/sys/solaris/sys/priocntl.d
rm -f %{buildroot}/usr/include/d/core/sys/solaris/sys/procset.d
rm -f %{buildroot}/usr/include/d/core/sys/solaris/sys/types.d
rm -f %{buildroot}/usr/include/d/core/sys/solaris/time.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/accctrl.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/aclapi.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/aclui.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/basetsd.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/basetyps.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/cderr.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/cguid.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/com.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/comcat.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/commctrl.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/commdlg.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/core.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/cpl.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/cplext.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/custcntl.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/dbghelp.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/dbghelp_types.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/dbt.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/dde.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/ddeml.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/dhcpcsdk.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/dlgs.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/dll.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/docobj.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/errorrep.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/exdisp.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/exdispid.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/httpext.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/idispids.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/imagehlp.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/imm.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/intshcut.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/ipexport.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/iphlpapi.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/ipifcons.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/iprtrmib.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/iptypes.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/isguids.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/lm.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/lmaccess.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/lmalert.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/lmapibuf.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/lmat.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/lmaudit.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/lmbrowsr.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/lmchdev.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/lmconfig.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/lmcons.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/lmerr.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/lmerrlog.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/lmmsg.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/lmremutl.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/lmrepl.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/lmserver.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/lmshare.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/lmsname.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/lmstats.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/lmsvc.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/lmuse.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/lmuseflg.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/lmwksta.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/lzexpand.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/mapi.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/mciavi.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/mcx.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/mgmtapi.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/mmsystem.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/msacm.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/mshtml.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/mswsock.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/nb30.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/nddeapi.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/nspapi.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/ntdef.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/ntdll.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/ntldap.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/ntsecapi.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/ntsecpkg.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/oaidl.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/objbase.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/objfwd.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/objidl.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/objsafe.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/ocidl.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/odbcinst.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/ole.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/ole2.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/ole2ver.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/oleacc.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/oleauto.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/olectl.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/olectlid.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/oledlg.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/oleidl.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/pbt.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/powrprof.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/prsht.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/psapi.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/rapi.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/ras.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/rasdlg.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/raserror.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/rassapi.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/reason.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/regstr.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/richedit.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/richole.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/rpc.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/rpcdce.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/rpcdce2.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/rpcdcep.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/rpcndr.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/rpcnsi.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/rpcnsip.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/rpcnterr.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/schannel.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/sdkddkver.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/secext.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/security.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/servprov.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/setupapi.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/shellapi.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/shldisp.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/shlguid.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/shlobj.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/shlwapi.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/snmp.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/sql.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/sqlext.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/sqltypes.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/sqlucode.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/sspi.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/stacktrace.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/stat.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/stdc/time.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/subauth.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/threadaux.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/tlhelp32.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/tmschema.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/unknwn.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/uuid.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/vfw.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/w32api.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/winbase.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/winber.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/wincon.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/wincrypt.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/windef.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/windows.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/winerror.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/wingdi.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/winhttp.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/wininet.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/winioctl.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/winldap.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/winnetwk.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/winnls.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/winnt.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/winperf.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/winreg.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/winsock2.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/winspool.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/winsvc.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/winuser.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/winver.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/wtsapi32.d
rm -f %{buildroot}/usr/include/d/core/sys/windows/wtypes.d
rm -f %{buildroot}/usr/include/d/core/thread/context.d
rm -f %{buildroot}/usr/include/d/core/thread/fiber.d
rm -f %{buildroot}/usr/include/d/core/thread/osthread.d
rm -f %{buildroot}/usr/include/d/core/thread/package.d
rm -f %{buildroot}/usr/include/d/core/thread/threadbase.d
rm -f %{buildroot}/usr/include/d/core/thread/threadgroup.d
rm -f %{buildroot}/usr/include/d/core/thread/types.d
rm -f %{buildroot}/usr/include/d/core/time.d
rm -f %{buildroot}/usr/include/d/core/vararg.d
rm -f %{buildroot}/usr/include/d/core/volatile.d
rm -f %{buildroot}/usr/include/d/etc/c/curl.d
rm -f %{buildroot}/usr/include/d/etc/c/odbc/sql.d
rm -f %{buildroot}/usr/include/d/etc/c/odbc/sqlext.d
rm -f %{buildroot}/usr/include/d/etc/c/odbc/sqltypes.d
rm -f %{buildroot}/usr/include/d/etc/c/odbc/sqlucode.d
rm -f %{buildroot}/usr/include/d/etc/c/sqlite3.d
rm -f %{buildroot}/usr/include/d/etc/c/zlib.d
rm -f %{buildroot}/usr/include/d/etc/linux/memoryerror.d
rm -f %{buildroot}/usr/include/d/ldc/asan.d
rm -f %{buildroot}/usr/include/d/ldc/attributes.d
rm -f %{buildroot}/usr/include/d/ldc/dcompute.d
rm -f %{buildroot}/usr/include/d/ldc/eh_msvc.d
rm -f %{buildroot}/usr/include/d/ldc/gccbuiltins_aarch64.di
rm -f %{buildroot}/usr/include/d/ldc/gccbuiltins_amdgcn.di
rm -f %{buildroot}/usr/include/d/ldc/gccbuiltins_arm.di
rm -f %{buildroot}/usr/include/d/ldc/gccbuiltins_mips.di
rm -f %{buildroot}/usr/include/d/ldc/gccbuiltins_nvvm.di
rm -f %{buildroot}/usr/include/d/ldc/gccbuiltins_ppc.di
rm -f %{buildroot}/usr/include/d/ldc/gccbuiltins_s390.di
rm -f %{buildroot}/usr/include/d/ldc/gccbuiltins_x86.di
rm -f %{buildroot}/usr/include/d/ldc/intrinsics.di
rm -f %{buildroot}/usr/include/d/ldc/libfuzzer.di
rm -f %{buildroot}/usr/include/d/ldc/llvmasm.di
rm -f %{buildroot}/usr/include/d/ldc/profile.di
rm -f %{buildroot}/usr/include/d/ldc/sanitizer_common.d
rm -f %{buildroot}/usr/include/d/ldc/sanitizers_optionally_linked.d
rm -f %{buildroot}/usr/include/d/ldc/simd.di
rm -f %{buildroot}/usr/include/d/object.d
rm -f %{buildroot}/usr/include/d/std/algorithm/comparison.d
rm -f %{buildroot}/usr/include/d/std/algorithm/internal.d
rm -f %{buildroot}/usr/include/d/std/algorithm/iteration.d
rm -f %{buildroot}/usr/include/d/std/algorithm/mutation.d
rm -f %{buildroot}/usr/include/d/std/algorithm/package.d
rm -f %{buildroot}/usr/include/d/std/algorithm/searching.d
rm -f %{buildroot}/usr/include/d/std/algorithm/setops.d
rm -f %{buildroot}/usr/include/d/std/algorithm/sorting.d
rm -f %{buildroot}/usr/include/d/std/array.d
rm -f %{buildroot}/usr/include/d/std/ascii.d
rm -f %{buildroot}/usr/include/d/std/base64.d
rm -f %{buildroot}/usr/include/d/std/bigint.d
rm -f %{buildroot}/usr/include/d/std/bitmanip.d
rm -f %{buildroot}/usr/include/d/std/compiler.d
rm -f %{buildroot}/usr/include/d/std/complex.d
rm -f %{buildroot}/usr/include/d/std/concurrency.d
rm -f %{buildroot}/usr/include/d/std/container/array.d
rm -f %{buildroot}/usr/include/d/std/container/binaryheap.d
rm -f %{buildroot}/usr/include/d/std/container/dlist.d
rm -f %{buildroot}/usr/include/d/std/container/package.d
rm -f %{buildroot}/usr/include/d/std/container/rbtree.d
rm -f %{buildroot}/usr/include/d/std/container/slist.d
rm -f %{buildroot}/usr/include/d/std/container/util.d
rm -f %{buildroot}/usr/include/d/std/conv.d
rm -f %{buildroot}/usr/include/d/std/csv.d
rm -f %{buildroot}/usr/include/d/std/datetime/date.d
rm -f %{buildroot}/usr/include/d/std/datetime/interval.d
rm -f %{buildroot}/usr/include/d/std/datetime/package.d
rm -f %{buildroot}/usr/include/d/std/datetime/stopwatch.d
rm -f %{buildroot}/usr/include/d/std/datetime/systime.d
rm -f %{buildroot}/usr/include/d/std/datetime/timezone.d
rm -f %{buildroot}/usr/include/d/std/demangle.d
rm -f %{buildroot}/usr/include/d/std/digest/crc.d
rm -f %{buildroot}/usr/include/d/std/digest/digest.d
rm -f %{buildroot}/usr/include/d/std/digest/hmac.d
rm -f %{buildroot}/usr/include/d/std/digest/md.d
rm -f %{buildroot}/usr/include/d/std/digest/murmurhash.d
rm -f %{buildroot}/usr/include/d/std/digest/package.d
rm -f %{buildroot}/usr/include/d/std/digest/ripemd.d
rm -f %{buildroot}/usr/include/d/std/digest/sha.d
rm -f %{buildroot}/usr/include/d/std/encoding.d
rm -f %{buildroot}/usr/include/d/std/exception.d
rm -f %{buildroot}/usr/include/d/std/experimental/allocator/building_blocks/affix_allocator.d
rm -f %{buildroot}/usr/include/d/std/experimental/allocator/building_blocks/aligned_block_list.d
rm -f %{buildroot}/usr/include/d/std/experimental/allocator/building_blocks/allocator_list.d
rm -f %{buildroot}/usr/include/d/std/experimental/allocator/building_blocks/ascending_page_allocator.d
rm -f %{buildroot}/usr/include/d/std/experimental/allocator/building_blocks/bitmapped_block.d
rm -f %{buildroot}/usr/include/d/std/experimental/allocator/building_blocks/bucketizer.d
rm -f %{buildroot}/usr/include/d/std/experimental/allocator/building_blocks/fallback_allocator.d
rm -f %{buildroot}/usr/include/d/std/experimental/allocator/building_blocks/free_list.d
rm -f %{buildroot}/usr/include/d/std/experimental/allocator/building_blocks/free_tree.d
rm -f %{buildroot}/usr/include/d/std/experimental/allocator/building_blocks/kernighan_ritchie.d
rm -f %{buildroot}/usr/include/d/std/experimental/allocator/building_blocks/null_allocator.d
rm -f %{buildroot}/usr/include/d/std/experimental/allocator/building_blocks/package.d
rm -f %{buildroot}/usr/include/d/std/experimental/allocator/building_blocks/quantizer.d
rm -f %{buildroot}/usr/include/d/std/experimental/allocator/building_blocks/region.d
rm -f %{buildroot}/usr/include/d/std/experimental/allocator/building_blocks/scoped_allocator.d
rm -f %{buildroot}/usr/include/d/std/experimental/allocator/building_blocks/segregator.d
rm -f %{buildroot}/usr/include/d/std/experimental/allocator/building_blocks/stats_collector.d
rm -f %{buildroot}/usr/include/d/std/experimental/allocator/common.d
rm -f %{buildroot}/usr/include/d/std/experimental/allocator/gc_allocator.d
rm -f %{buildroot}/usr/include/d/std/experimental/allocator/mallocator.d
rm -f %{buildroot}/usr/include/d/std/experimental/allocator/mmap_allocator.d
rm -f %{buildroot}/usr/include/d/std/experimental/allocator/package.d
rm -f %{buildroot}/usr/include/d/std/experimental/allocator/showcase.d
rm -f %{buildroot}/usr/include/d/std/experimental/allocator/typed.d
rm -f %{buildroot}/usr/include/d/std/experimental/checkedint.d
rm -f %{buildroot}/usr/include/d/std/experimental/logger/core.d
rm -f %{buildroot}/usr/include/d/std/experimental/logger/filelogger.d
rm -f %{buildroot}/usr/include/d/std/experimental/logger/multilogger.d
rm -f %{buildroot}/usr/include/d/std/experimental/logger/nulllogger.d
rm -f %{buildroot}/usr/include/d/std/experimental/logger/package.d
rm -f %{buildroot}/usr/include/d/std/experimental/typecons.d
rm -f %{buildroot}/usr/include/d/std/file.d
rm -f %{buildroot}/usr/include/d/std/format.d
rm -f %{buildroot}/usr/include/d/std/functional.d
rm -f %{buildroot}/usr/include/d/std/getopt.d
rm -f %{buildroot}/usr/include/d/std/internal/attributes.d
rm -f %{buildroot}/usr/include/d/std/internal/cstring.d
rm -f %{buildroot}/usr/include/d/std/internal/digest/sha_SSSE3.d
rm -f %{buildroot}/usr/include/d/std/internal/math/biguintarm.d
rm -f %{buildroot}/usr/include/d/std/internal/math/biguintcore.d
rm -f %{buildroot}/usr/include/d/std/internal/math/biguintnoasm.d
rm -f %{buildroot}/usr/include/d/std/internal/math/biguintx86.d
rm -f %{buildroot}/usr/include/d/std/internal/math/errorfunction.d
rm -f %{buildroot}/usr/include/d/std/internal/math/gammafunction.d
rm -f %{buildroot}/usr/include/d/std/internal/memory.d
rm -f %{buildroot}/usr/include/d/std/internal/scopebuffer.d
rm -f %{buildroot}/usr/include/d/std/internal/test/dummyrange.d
rm -f %{buildroot}/usr/include/d/std/internal/test/range.d
rm -f %{buildroot}/usr/include/d/std/internal/test/uda.d
rm -f %{buildroot}/usr/include/d/std/internal/unicode_comp.d
rm -f %{buildroot}/usr/include/d/std/internal/unicode_decomp.d
rm -f %{buildroot}/usr/include/d/std/internal/unicode_grapheme.d
rm -f %{buildroot}/usr/include/d/std/internal/unicode_norm.d
rm -f %{buildroot}/usr/include/d/std/internal/unicode_tables.d
rm -f %{buildroot}/usr/include/d/std/internal/windows/advapi32.d
rm -f %{buildroot}/usr/include/d/std/json.d
rm -f %{buildroot}/usr/include/d/std/math.d
rm -f %{buildroot}/usr/include/d/std/mathspecial.d
rm -f %{buildroot}/usr/include/d/std/meta.d
rm -f %{buildroot}/usr/include/d/std/mmfile.d
rm -f %{buildroot}/usr/include/d/std/net/curl.d
rm -f %{buildroot}/usr/include/d/std/net/isemail.d
rm -f %{buildroot}/usr/include/d/std/numeric.d
rm -f %{buildroot}/usr/include/d/std/outbuffer.d
rm -f %{buildroot}/usr/include/d/std/package.d
rm -f %{buildroot}/usr/include/d/std/parallelism.d
rm -f %{buildroot}/usr/include/d/std/path.d
rm -f %{buildroot}/usr/include/d/std/process.d
rm -f %{buildroot}/usr/include/d/std/random.d
rm -f %{buildroot}/usr/include/d/std/range/interfaces.d
rm -f %{buildroot}/usr/include/d/std/range/package.d
rm -f %{buildroot}/usr/include/d/std/range/primitives.d
rm -f %{buildroot}/usr/include/d/std/regex/internal/backtracking.d
rm -f %{buildroot}/usr/include/d/std/regex/internal/generator.d
rm -f %{buildroot}/usr/include/d/std/regex/internal/ir.d
rm -f %{buildroot}/usr/include/d/std/regex/internal/kickstart.d
rm -f %{buildroot}/usr/include/d/std/regex/internal/parser.d
rm -f %{buildroot}/usr/include/d/std/regex/internal/tests.d
rm -f %{buildroot}/usr/include/d/std/regex/internal/tests2.d
rm -f %{buildroot}/usr/include/d/std/regex/internal/thompson.d
rm -f %{buildroot}/usr/include/d/std/regex/package.d
rm -f %{buildroot}/usr/include/d/std/signals.d
rm -f %{buildroot}/usr/include/d/std/socket.d
rm -f %{buildroot}/usr/include/d/std/stdint.d
rm -f %{buildroot}/usr/include/d/std/stdio.d
rm -f %{buildroot}/usr/include/d/std/string.d
rm -f %{buildroot}/usr/include/d/std/system.d
rm -f %{buildroot}/usr/include/d/std/traits.d
rm -f %{buildroot}/usr/include/d/std/typecons.d
rm -f %{buildroot}/usr/include/d/std/typetuple.d
rm -f %{buildroot}/usr/include/d/std/uni/package.d
rm -f %{buildroot}/usr/include/d/std/uri.d
rm -f %{buildroot}/usr/include/d/std/utf.d
rm -f %{buildroot}/usr/include/d/std/uuid.d
rm -f %{buildroot}/usr/include/d/std/variant.d
rm -f %{buildroot}/usr/include/d/std/windows/charset.d
rm -f %{buildroot}/usr/include/d/std/windows/registry.d
rm -f %{buildroot}/usr/include/d/std/windows/syserror.d
rm -f %{buildroot}/usr/include/d/std/xml.d
rm -f %{buildroot}/usr/include/d/std/zip.d
rm -f %{buildroot}/usr/include/d/std/zlib.d
rm -f %{buildroot}/usr/lib64/libdruntime-ldc-debug-shared.so
rm -f %{buildroot}/usr/lib64/libdruntime-ldc-shared.so
rm -f %{buildroot}/usr/lib64/libphobos2-ldc-debug-shared.so
rm -f %{buildroot}/usr/lib64/libphobos2-ldc-shared.so
rm -f %{buildroot}/usr/share/defaults/etc/bash_completion.d/ldc2
rm -f %{buildroot}/usr/share/defaults/etc/ldc2.conf

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libdruntime-ldc-debug-shared.so.2.0.95
/usr/lib64/libdruntime-ldc-debug-shared.so.95
/usr/lib64/libdruntime-ldc-shared.so.2.0.95
/usr/lib64/libdruntime-ldc-shared.so.95
/usr/lib64/libphobos2-ldc-debug-shared.so.2.0.95
/usr/lib64/libphobos2-ldc-debug-shared.so.95
/usr/lib64/libphobos2-ldc-shared.so.2.0.95
/usr/lib64/libphobos2-ldc-shared.so.95

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-ldc-soname95/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
